[theme]
primaryColor="#1DB954"
backgroundColor="#191414"
secondaryBackgroundColor="#535353"
textColor="#FFFFFF"
font="sans serif"

[server]
maxUploadSize=50
enableStaticServing=true
enableCORS=false

[browser]
gatherUsageStats=false

[runner]
fastReruns=true

[global]
developmentMode=false
